workflows:
  ios-webview-release:
    name: iOS WebView Release
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: "com.corearsitek.webview"
        APP_NAME: "CoreArsitek"
    scripts:
      - name: Re-generate Flutter iOS project
        script: |
          rm -rf ios
          flutter create .
      - name: Overwrite Info.plist for WebView permissions
        script: |
          cat > ios/Runner/Info.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>CFBundleName</key>
            <string>$(APP_NAME)</string>
            <key>CFBundleIdentifier</key>
            <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
            <key>CFBundleVersion</key>
            <string>1.0.0</string>
            <key>CFBundleShortVersionString</key>
            <string>1.0.0</string>
            <key>UILaunchStoryboardName</key>
            <string>LaunchScreen</string>
            <key>UIRequiresFullScreen</key>
            <true/>
            <key>NSAppTransportSecurity</key>
            <dict>
              <key>NSAllowsArbitraryLoads</key>
              <true/>
            </dict>
          </dict>
          </plist>
          EOF
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS release (no codesign)
        script: flutter build ios --release --no-codesign
      - name: Package .app into .ipa
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - build/ios/iphoneos/Runner.ipa
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - deniafrizal2904@gmail.com
